enum NetworkExceptionTypes {
  requestCancelled,
  unauthorisedRequest,
  badRequest,
  notFound,
  methodIsNotAllowed,
  notAcceptable,
  requestTimeout,
  sendTimeout,
  conflict,
  internalServerError,
  notImplemented,
  serviceUnavailable,
  noInternetConnection,
  formatException,
  unableToProcess,
  defaultError,
  unexpectedError
}
